package detection;

/**
 * The Enum is used to set reasons why a feature collection is considered a code smell. 
 * Can be used for later filtering for more complex configurations
 */
public enum EnumReason {
	LARGEFEATURE_LOFCTOMEANLOFC,
	LARGEFEATURE_LOFCTOLOC,
	LARGEFEATURE_NUMBERLOFC,
	LARGEFEATURE_NUMBERNOFC,
	
	ANNOTATIONBUNDLE_LOFCTOLOC,
	ANNOTATIONBUNDLE_LOACTOLOC,
	ANNOTATIONBUNDLE_NUMBERFEATURECONSTANTS,
	ANNOTATIONBUNDLE_NUMBERFEATURECONSTNONDUP,
	ANNOTATIONBUNDLE_NUMBERNEGATIONS,
	ANNOTATIONBUNDLE_NUMBERNESTINGDEPTHMIN,
	ANNOTATIONBUNDLE_NUMBERNESTINGSUM,
	ANNOTATIONBUNDLE_NUMBERFEATURELOC,
	
	ANNOTATIONFILE_LOFCTOLOC,
	ANNOTATIONFILE_LOACTOLOC,
	ANNOTATIONFILE_NUMBERFEATURECONSTANTS,
	ANNOTATIONFILE_NUMBERFEATURECONSTNONDUP,
	ANNOTATIONFILE_NUMBERNEGATIONS,
	ANNOTATIONFILE_NUMBERNESTINGDEPTHMIN,
	ANNOTATIONFILE_NUMBERNESTINGSUM,
	ANNOTATIONFILE_NUMBERFEATURELOC,
	
	SHOTGUNSURGERY_NOFCOSUMNOFC,
	SHOTGUNSURGERY_NUMBERCOMPILATIONUNITS
}
