package detection;

/**
 * The Enum is used to set reasons why a feature collection is considered a code smell. 
 * Can be used for later filtering for more complex configurations
 */
public enum EnumReason {
	LARGEFEATURE_BIGGERMEANLOFC,
	LARGEFEATURE_BIGPROJECTPART,
	
	ANNOTATIONBUNDLE_LOFCTOLOC,
	ANNOTATIONBUNDLE_LOACTOLOC,
	ANNOTATIONBUNDLE_NUMBERFEATURELOCS,
	ANNOTATIONBUNDLE_NUMBERFEATURECONST,
	ANNOTATIONBUNDLE_NUMBERNEGATIONS,
	ANNOTATIONBUNDLE_NUMBERNESTINGDEPTHMAX,
	ANNOTATIONBUNDLE_NUMBERNESTINGSUM,
	
	SHOTGUNSURGERY_NOFLTOSUMNOFL,
	SHOTGUNSURGERY_NUMBERCOMPILATIONUNITS
}
